services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    ports:
      - 443:443
    networks:
    - inception_network
    restart: always  # requis suject crash contneur == restart

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    volumes:
      - wordpress:/var/www/html/  # cherche les fichiers et ensuite redirige dans path/thsykas
    networks:
    - inception_network
    env_file:
      - .env  # acces a toutes les var .env
    restart: always

  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    volumes:
      - mariadb:/var/lib/mysql
    networks:
    - inception_network
    env_file:
      - .env
    restart: always


volumes:
  mariadb:
    driver: local  # local sur (MACHINE)
    # list of param for volume
    driver_opts:
      type: none
      o: bind
      device: /home/thsykas/data/mariadb  # store volume in target

  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/thsykas/data/wordpress

# network is for make communicate service beetween containeurs
networks:
  inception_network:
    driver: bridge