services:
  nginx:
    build: ./requirement/nginx
    container_name: nginx
    ports:
      - 443:443
    restart: always  # requis suject crash contneur == restart

  wordpress:
    volumes:
      - wordpress:var/www/html/  # cherche les fichiers et ensuite redirige dans path/thsykas
    restart: always

  mariadb:
    volumes:
      - mariadb:/var/lib/mysql
    restart: always


volumes:
  mariadb:
    driver: local  # local sur (MACHINE)
    # list of param for volume
    driver_opts:
      type: none
      o: bind
      device: /home/thsykas/data/mariadb  # store volume in target

  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/thsykas/data/wordpress

# network is for make communicate service beetween containeurs
networks:
