# www.conf sert a conf le php-fpm ouvrir uncanal de comm sur un port e.g 9000
# pour communiquer avec et exec les script php envoyer pas nginx
[www]

# 0.0.0.0 == ecoute toutes les interfaces resau
listen = 0.0.0.0:9000

# empeche le clear des variables sys hors on doit lire MY_SQL_DATA
clear_env = false

user = www-data
group = www-data


# mem RAM gestion
pm = dynamic  # creat user
pm.max_children = 5  # 5 worker sim
pm.start_servers = 2
pm.min_spare_servers = 1
pm.max_spare_servers = 3